### ISSUE TITLE
Auto turn off when vibrate.

### ISSUE THREAD

**Issue by DilVika** [grayver/mi-vigem#6]
Hello, This is very usefull tool. But I have a problem, that when every time vibrate was active, the Gamepad auto turning off?

One more question: How can I get a newer Vigem driver without build the repo, and which one I should use? :/

**Comment by grayver** [comment]
Hello!

> every time vibrate was active, the Gamepad auto turning off

Could you provide more details? Does gamepad turn off physically? Or it just stops sending input?

> How can I get a newer Vigem driver without build the repo, and which one I should use?

I use version 1.16.116 without any problem.

**Comment by DilVika** [comment]
>Could you provide more details? Does gamepad turn off physically? Or it just stops sending input?
> 
 It turn off physically.

**Comment by grayver** [comment]
> It turn off physically.

Hmm.. Did you check the battery level? It looks like your gamepad turns off due voltage drop. Vibration consumes a lot of energy and can lead to a voltage drop. Gamepad treats this as a critical low battery level and turns off.

MiViGem doesn't have ability to turn on/turn off a gamepad. It just can send vibration commands (turn on vibration, turn off vibration, change vibration level).

**Comment by DilVika** [comment]
Thanks for your respond. Should I use rechargable instead of ALkalines?

**Comment by grayver** [comment]
Actually, it doesn't matter. Just use good batteries. Not the cheapest.
