### ISSUE TITLE
杂牌手柄驱动问题

### ISSUE THREAD

**Issue by aizaimosaou** [grayver/mi-vigem#7]
老哥你好，我几年前买了一个杂牌手柄，是惠康的we4800,用各种各样的模拟都不太行。我自己测试过了，在xb360ce中，所有的按键都有效果。
由于市面上的软件都不是很好，我先拆开了we4800手柄，发现里面的构建很简单。
我就寻思着能不能自己写一个驱动，就像老哥你写的小米手柄驱动一样。
在这里我就很感谢老哥了，大学时代我用你的驱动，成功的运行了小米蓝牙手柄。体验效果真的很好。但我在今天才发现是你写的。非常感谢老哥带来的快乐。
在这里我也斗胆问一句，能否请老哥教教我具体的开发流程？我可以贡献我拆卸的手柄具体照片细节。供老哥查看。
很期待老哥的回复

**Comment by aizaimosaou** [comment]
我重新解释下，我那个杂牌手柄全部模拟都可以通过，但是在游戏界面却失灵无效。

**Comment by grayver** [comment]
你好！ 实际上，我没有写驱动程序。 我刚刚在通用Windows HID驱动程序和ViGEM模拟器软件之间建立了一座桥梁（因此，它模拟了XBox360游戏控制器）。 如果要执行相同的操作，则需要控制器的文档或对控制器键映射进行反向工程。 在我的工作中，我依靠另一位开发人员（https://github.com/irungentoo/Xiaomi_gamepad）提供的研究结果来获取关键映射。 但是，如果您熟悉C / C ++开发和HID基础知识，并不是很难。
