### ISSUE TITLE
It doesn't work on Windows 11, becomes double tapped.

### ISSUE THREAD

**Issue by samjoy1005** [grayver/mi-vigem#8]
It doesn't work on Windows 11, becomes double tapped.

**Comment by grayver** [comment]
Sorry for the long delay with answer. Mi-ViGEm creates virtual XBox 360 gamepad in parallel with original Mi Gamepad device. Some applications read input from both devices and this leads to double input issues. There is no way to avoid this on user application level. As a workaround you can try kernel-level driver solution like [HidHide](https://github.com/ViGEm/HidHide).
